name: deploy-myApp

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - "posts/**"
      - "comments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['client', 'posts', 'comments']
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        working-directory: ${{ matrix.directory }}
        run: |
          npm install
          npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
          CI: false

      - name: Set up AWS CLI
        if: matrix.directory == 'client'
        uses: shinyinc/action-aws-cli@v1.2

      - name: AWS S3 Sync
        if: matrix.directory == 'client'
        run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: CloudFront Invalidation
        if: matrix.directory == 'client'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
          AWS_DEFAULT_REGION: us-east-2
